# 환경세팅 

### 	1. DATA 수집 및 분석을 위한 수업전 환경을 설정하고 필요한 프로그램을 설치

#### 			python 설치 

​					윈도우에서 파이썬 설치하기

**1)** 우선 파이썬 공식 홈페이지의 다운로드 페이지([http://www.python.org/downloads](http://www.python.org/downloads/))에서 윈도우용 파이썬 언어 패키지를 다운로드한다. 다음 화면에서 Python 3.x로 시작하는 버전 중 3.8.x 을 윈도우 인스톨러를 다운로드하자(이 글을 작성하는 시점의 최신 버전은 3.8.7이다).

![image-20210123190506670](https://user-images.githubusercontent.com/25717861/105575292-efde9800-5dad-11eb-9b23-faccd20e6798.png)



![image-20210123190845399](https://user-images.githubusercontent.com/25717861/105575370-80b57380-5dae-11eb-893c-d2e5e1887466.png)

**2)인스톨러를 실행한 후에 "Install Now"를 선택하면 바로 설치가 진행된다.**

파이썬이 어느 곳에서든지 실행될 수 있도록 "Add Python3.8 to PATH" 옵션을 반드시 선택해야 한다.

![image-20210123191346607](https://user-images.githubusercontent.com/25717861/105575461-249f1f00-5daf-11eb-862d-584a84bea93e.png)

> ※ "Add Python 3.7 to PATH" 옵션을 누락하면 이후 실습할 때 오류가 발생할 수 있다. 만약 Python이 설치되는 경로와 PATH에 대한 사전 지식이 있는 사용자라면 이 옵션을 생략해도 된다.

##### 3)설치가 완료되면 [close]를 클릭하여 종료한다.

파이썬이 정상적으로 설치되었다면 다음 그림과 같이 프로그램 메뉴에서 확인할 수 있다.

**[시작 → 모든 프로그램 → Python 3.8]**



​				

####  		 jupyter notebook 설치

​			windows 10  기준으로 cmd 창을 열고 다음과 같은 명령어를 이용해서 설치

```powershell
pip install jupyter
```





####  		 jupyter notebook 실행

```powershell
C:\Users\user>cd 

C:\>cd apps

C:\apps>mkdir finace_data

C:\apps>cd finace_data

C:\apps\finace_data>jupyter notebook

```


![image-20210123192250643](https://user-images.githubusercontent.com/25717861/105575640-7a27fb80-5db0-11eb-9004-62d97901cb92.png)

## FinanceDataReader을 이용한 분석

* 한국 주식 가격, 미국주식 가격, 지수, 환율, 암호화폐 가격, 종목 리스팅 등 금융 데이터 수집 라이브러리

* [FinanceData/FinanceDataReader: Financial data reader](https://github.com/FinanceData/FinanceDataReader)
* [FinanceDataReader 사용자 안내서 | FinanceData](https://financedata.github.io/posts/finance-data-reader-users-guide.html)
* https://pandas-datareader.readthedocs.io/en/latest/readers/index.html

# finance-datareader 설치

In [1]:
!pip install finance-datareader

Requirement already satisfied: finance-datareader in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (0.9.14)
Requirement already satisfied: requests-file in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from finance-datareader) (1.5.1)
Requirement already satisfied: lxml in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from finance-datareader) (4.6.2)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from finance-datareader) (4.56.0)
Requirement already satisfied: pandas>=0.19.2 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from finance-datareader) (1.2.0)
Requirement already satisfied: requests>=2.3.0 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from finance-datareader) (2.25.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from pandas>=0.19.2->finance-datareader) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from pandas>=0.19.2->finance-datareader) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from pandas>=0.19.2->finance-datareader) (2020.5)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->finance-datareader) (1.15.0)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.3.0->finance-datareader) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.3.0->finance-datareader) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.3.0->finance-datareader) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.3.0->finance-datareader) (2.10)

# 라이브러리 불러오기

### 데이터프레임을 활용한 다양한 활용을 위한 pandas  불러오기

In [21]:
import pandas as pd
import numpy as np

## 한국거래수 상장종목 전체 가져오기

In [22]:
# FinanceDataReader 를 fdr 별칭으로 불러오는 방법으로
import FinanceDataReader as fdr

fdr.__version__

'0.9.14'

##### KRX : KRX 종목 전체
##### KOSPI : KOSPI 종목
##### KOSDAQ : KOSDAQ 종목
##### KONEX : KONEX 종목
##### NASDAQ : 나스닥 종목
##### NYSE : 뉴욕증권거래소 종목
##### SP500 : S&P500 종목

In [23]:
#한국 거래소 상장종목 가져오기
data_krx = fdr.StockListing('KRX')
data_nasdaq = fdr.StockListing('NASDAQ')

100%|███████████████████████████████████████████████████████████████████████████████████| 3345/3345 [00:04<00:00, 752.62it/s]

In [24]:
data_krx.shape

(6676, 10)

In [25]:
#data_krx의 전체적인 데이타의 특성정보를 확인할 수 있다.
data_krx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6676 entries, 0 to 6675
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          6676 non-null   object
 1   Market          6676 non-null   object
 2   Name            6676 non-null   object
 3   Sector          2412 non-null   object
 4   Industry        2393 non-null   object
 5   ListingDate     2412 non-null   datetime64[ns]
 6   SettleMonth     2412 non-null   object
 7   Representative  2412 non-null   object
 8   HomePage        2240 non-null   object
 9   Region          2412 non-null   object
dtypes: datetime64[ns](1), object(9)
memory usage: 573.7+ KB

In [26]:
#data_krx의 전체적인 데이타의 기술통계값을 확인할 수 있다.
data_krx.describe()

<ipython-input-26-0dbf0be939f1>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  data_krx.describe()

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
count,6676,6676,6676,2412,2393,2412,2412,2412,2240,2412
unique,6676,3,6676,158,2241,1777,9,2297,2219,21
top,57FM62,KOSPI,스타플렉스,특수 목적용 기계 제조업,기업인수합병,1976-06-30 00:00:00,12월,-,http://www.sempio.com,서울특별시
freq,1,5039,1,141,36,8,2352,5,2,972
first,NaN,NaN,NaN,NaN,NaN,1956-03-03 00:00:00,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,2021-01-21 00:00:00,NaN,NaN,NaN,NaN

In [27]:
data_krx.columns

Index(['Symbol', 'Market', 'Name', 'Sector', 'Industry', 'ListingDate',
       'SettleMonth', 'Representative', 'HomePage', 'Region'],
      dtype='object')

In [28]:
data_krx['Representative'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6671     True
6672     True
6673    False
6674    False
6675    False
Name: Representative, Length: 6676, dtype: bool

## 파일로 저장하고 불러오기
<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite1.svg">

### DataFrame
<img src="https://pandas.pydata.org/docs/_images/01_table_dataframe1.svg">

In [32]:
data_krx

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,이현우,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...
6671,000547,KOSPI,흥국화재2우B,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6672,000545,KOSPI,흥국화재우,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6673,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
6674,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호, 염두성 (각자대표)",http://www.heerim.com,서울특별시
6675,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [33]:
data_krx.to_csv('krx_data.csv')

In [34]:
pd.read_csv('krx_data.csv')

,Unnamed: 0,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,이현우,http://www.ajnet.co.kr,서울특별시
2,2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...,...
6671,6671,000547,KOSPI,흥국화재2우B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6672,6672,000545,KOSPI,흥국화재우,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6673,6673,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
6674,6674,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호, 염두성 (각자대표)",http://www.heerim.com,서울특별시
6675,6675,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [35]:
data_krx.to_csv('krx_data.csv', encoding="utf-8-sig")

In [36]:
pd.read_csv('krx_data.csv')

,Unnamed: 0,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,이현우,http://www.ajnet.co.kr,서울특별시
2,2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...,...
6671,6671,000547,KOSPI,흥국화재2우B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6672,6672,000545,KOSPI,흥국화재우,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6673,6673,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
6674,6674,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호, 염두성 (각자대표)",http://www.heerim.com,서울특별시
6675,6675,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [37]:
data_krx.to_csv('krx_data.csv', encoding="utf-8-sig", index=False)

In [38]:
pd.read_csv('krx_data.csv')

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,이현우,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...
6671,000547,KOSPI,흥국화재2우B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6672,000545,KOSPI,흥국화재우,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6673,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
6674,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호, 염두성 (각자대표)",http://www.heerim.com,서울특별시
6675,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [39]:
# Name 컬럼 하나만 가져옵니다.
data_krx['Name']

0            3S
1        AJ네트웍스
2         AK홀딩스
3        APS홀딩스
4         AP시스템
         ...
6671    흥국화재2우B
6672      흥국화재우
6673       흥아해운
6674         희림
6675         힘스
Name: Name, Length: 6676, dtype: object

In [41]:
# 0번째 행만 가져옵니다. 행인덱스를 가져올때는 .loc를 사용합니다.
# loc는 위치(locate)를 의미합니다.
data_krx.loc[0]

Symbol                          060310
Market                          KOSDAQ
Name                                3S
Sector                   특수 목적용 기계 제조업
Industry                   반도체 웨이퍼 캐리어
ListingDate        2002-04-23 00:00:00
SettleMonth                        03월
Representative      박종익, 김세완 (각자 대표이사)
HomePage          http://www.3sref.com
Region                           서울특별시
Name: 0, dtype: object

In [43]:
# df.loc[0] 의 type을 봅니다.
type(data_krx.loc[0])

pandas.core.series.Series

In [44]:
# 여러 컬럼을 지정할 때는 리스트 형태로 묶어주어야 합니다. 
# 2차원 행렬은 대괄호가 [] 2개가 있다는 것을 기억해 주세요.
data_krx[['Name','Industry']]

         Name                        Industry
0          3S                     반도체 웨이퍼 캐리어
1      AJ네트웍스             렌탈(파렛트, OA장비, 건설장비)
2       AK홀딩스                            지주사업
3      APS홀딩스                     인터넷 트래픽 솔루션
4       AP시스템                     디스플레이 제조 장비
...       ...                             ...
6671  흥국화재2우B                             NaN
6672    흥국화재우                             NaN
6673     흥아해운                  외항화물운송업(케미컬탱커)
6674       희림                       설계 및 감리용역
6675       힘스  OLED Mask 인장기, OLED Mask 검사기 등

[6676 rows x 2 columns]

In [46]:
# 여러 개의 행을 가져올 때도 [] 대괄호를 통해 리스트 형태로 묶어줍니다.
data_krx.loc[[0,3,5,7]]

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
5,211270,KOSDAQ,AP위성,통신 및 방송 장비 제조업,위성통신 단말기,2016-03-04,12월,류장수,http://www.apsi.co.kr,서울특별시
7,295820,KOSPI,ARIRANG 200동일가중,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [47]:
import FinanceDataReader as fdr
import pandas as pd
import seaborn as sns
import numpy as np

In [50]:
# FX 환율, 1995 ~ 현재
usdkrw = fdr.DataReader('USD/KRW', '1995-01-01')

In [49]:
fdr.DataReader('USD/KRW', '1995-01-01', '2000-12-30')

              Close     Open     High      Low  Change
Date
1995-01-02   788.50   788.50   788.50   788.50  0.0000
1995-01-03   788.65   788.05   788.85   787.55  0.0002
1995-01-04   789.95   788.65   790.05   788.45  0.0016
1995-01-05   789.90   789.80   790.20   789.30 -0.0001
1995-01-06   791.55   789.75   791.65   789.65  0.0021
...             ...      ...      ...      ...     ...
2000-12-25  1237.15  1237.15  1237.15  1237.15  0.0000
2000-12-26  1252.25  1252.25  1252.25  1240.25  0.0122
2000-12-27  1258.50  1258.50  1275.50  1253.50  0.0050
2000-12-28  1252.50  1257.50  1261.00  1244.50 -0.0048
2000-12-29  1265.00  1254.00  1265.00  1250.50  0.0100

[1559 rows x 5 columns]

In [52]:
usdkrw.to_csv("한국환율.csv", encoding="utf-8-sig")

In [53]:
pd.read_csv('한국환율.csv')

            Date    Close     Open     High      Low  Change
0     1995-01-02   788.50   788.50   788.50   788.50  0.0000
1     1995-01-03   788.65   788.05   788.85   787.55  0.0002
2     1995-01-04   789.95   788.65   790.05   788.45  0.0016
3     1995-01-05   789.90   789.80   790.20   789.30 -0.0001
4     1995-01-06   791.55   789.75   791.65   789.65  0.0021
...          ...      ...      ...      ...      ...     ...
6785  2021-01-18  1102.52  1104.26  1108.42  1102.28 -0.0007
6786  2021-01-19  1101.44  1104.18  1106.17  1100.20 -0.0010
6787  2021-01-20  1096.35  1102.44  1103.39  1096.88 -0.0046
6788  2021-01-21  1099.88  1097.35  1102.67  1096.59  0.0032
6789  2021-01-22  1105.41  1099.97  1107.29  1098.95  0.0050

[6790 rows x 6 columns]